### ISSUE TITLE
Missing header file

### ISSUE THREAD

**Issue by kapil-iitk** [matejx/avr_isp_bub#2]
Thank you for this project. Can you please point out where I can get the missing header file (I already downloaded your avr_libs)? While compiling the main, it says ee_24.h is missing. Also, should I put some of your avr_lib files in the mat folder? Is there any changes required to use at24C64 EEPROM instead of at24C512? 

Thank you.

**Comment by matejx** [comment]
I removed unmaintained sources from the library, one of which was ee_24. I've included them in the project now, so it should work after you update. Thanks for pointing this out.

I have the library in mat folder, so if you want to use the sources unchanged, put it two directories above the project directory  (take a look at makefile variable LIBDIR).

Any EEPROM that uses 2 byte addressing should work.

**Comment by kapil-iitk** [comment]
Thank you for sharing the missing header file. Still, there are some issues that you can include in the makefile for the successful generation of the hex file.
1. Put all the header files from avr_lib-master into mat folder.
2. in makefile, LIBDIR =""   it must be empty or commented
3. newer avr-gcc (esp. V13) generate warning therefore add CFLAGS += --param=min-pagesize=0 in the makefile.
4. for successful compilation, create a .dep folder or in the makefile, after build: add the following line mkdir .dep

Thank you once again for the help.
